apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: password
  restartPolicy: Never
  imagePullSecrets:
  - name: regcred
