apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-app
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data-volume
      mountPath: /data
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
  volumes:
  - name: data-volume
    emptyDir: {}
