apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - name: debian
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Hello World' >> /html/index.html; sleep 5; done"]
    volumeMounts:
    - name: html
      mountPath: /html
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  volumes:
  - name: html
    hostPath:
      path: /path/to/html/folder/ on/your/local/machine
